# ============================================
# Issam : Spring Security JPA - Base personnalisée
# Auteur : Issam ABOUSSAKKINE
# ============================================

server.port=8089
spring.application.name=spring-security-jpa-issam

# Issam : Base de données avec mon nom
spring.datasource.url=jdbc:mysql://localhost:3306/security_db_issam?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false